int n=0; 
int day=1;
int check=1;
int scene=1;
int pos[6][6];
int w = 180;
int grid[6][6] = {0};
Sprite *image_index;
Texture *image_texture;
Sprite sprite[17];
Texture t;
Font* font;
Text* text;
Text* end_game;